cortex-command-community/Cortex-Command-Community-Project

Managers/LuaMan.cpp
I described the issue [here](https://github.com/cortex-command-community/Cortex-Command-Community-Project-Source/issues/583#issue-2061123402) in a Source repo Issue.
The tl;dr is that this error should have never been printed here, since mods rely on `fgets()` to return `nullptr` when the end of a file that ends with a newline is reached, which is corroborated by `fgets()` [its man page](https://linux.die.net/man/3/fgets):
> fgets() return *s* on success, and NULL on error or when end of file occurs while no characters have been read.
The important thing to note here is that `FileReadLine()` already correctly returns an empty string when one attempts to read the end of the file.
And no, there is literally no other way for a mod to know whether `FileReadLine()` would print that error on …
=> Fix misleading error printing by FileReadLine()

Managers/LuaMan.cpp, Managers/LuaMan.h
When `GetDirectoryList()` or `GetFileList()` were called recursively, the inner call would overwrite the data from the outer call. This is very bad, of course. So I made them reentrant, based on the already reentrant `GetWounds()` that also returns a `std::vector`.
I also made a minimal reproducible example [mod](https://github.com/cortex-command-community/Cortex-Command-Community-Project/files/13837697/bug.rte.zip) to demonstrate how this PR changes the list functions their behavior.
=> Make GetDirectoryList and GetFileList reentrant

Source/Managers/PostProcessMan.cpp
Miscopy from MIN filter, which accepts wider variety of options.
MAG filter only accepts GL_LINEAR and GL_NEAREST.
=> Use correct MAG filter for GL texture

Source/Entities/Activity.cpp, Source/Entities/Actor.cpp, Source/Managers/LuaMan.cpp, Source/Managers/MovableMan.cpp, Source/Managers/SettingsMan.cpp, Source/Managers/SettingsMan.h
Some settings to be able to adjust how multithreaded the game is, for the sake of debug testing for determinism
=> Multithreading Settings

Source/Managers/LuaMan.cpp, Source/System/RTETools.cpp
> Perf concerns about how many io operations are required for getting the proper path, but ah well, not much choice I guess
I was planning to, but forgot to add an early return on Linux when the full path is already known to exist.
=> Early return when full path exists on Linux

Source/Entities/MovableObject.cpp, Source/Main.cpp
Fixes https://github.com/cortex-command-community/Cortex-Command-Community-Project/issues/20 and https://github.com/cortex-command-community/Cortex-Command-Community-Project/issues/21
=> Lua Crash Fixes

CHANGELOG.md, Source/Managers/LuaMan.cpp, Source/Managers/LuaMan.h
So the timeline of events is that:
1. My original implementation of `DirectoryList()` forgot the logic that disallows escaping the game's directory.
2. I noticed this, and panicked so hard that I let my recent filesystem functions PR disallow mods from doing anything outside of their directory, just to be safe.
3. Today I tried to actually use my new filesystem functions in ModMod, and quickly noticed that my mod entirely broke, since it wasn't able to iterate over the entries in `Data/` or `Mods/` anymore. I also realized that loads of functionality I am still planning to add, like being able to create or rename mod directories in-game, was now entirely impossible. But there isn't anything fundamentally unsafe with these things!
So, this PR finds a good middle ground, where the game's …
=> Let filesystem functions be slightly less strict

CHANGELOG.md, Source/Lua/LuaBindingsManagers.cpp, Source/Managers/SceneMan.cpp, Source/Managers/SceneMan.h
Added CastTerrainPenetrationRay to SceneMan, which stops after passing through a given amount of terrain material strength and returns true if stopped. This functionality is mostly already present in CastUnseenRay and all its siblings, but they all affect fog of war, so i figured it was nice to have this functionality without messing with fog of war.
=> Added CastTerrainPenetrationRay to SceneMan

.github/actions/get-game-version/action.yaml, .github/workflows/release.yaml
Adds a new action that uses bash wizardry to grab the current game version (from `Source/System/GameVersion.h`) and use the value in all text/tags for the release.
=> feat: make the master release script pull game version from committed files

CHANGELOG.md, Data/Missions.rte/Activities/DummyAssault.lua
Was just one erroneous line that always ran in StartActivity instead of only in StartNewGame
=> Fix Dummy Assault always resetting funds even on loading games

CHANGELOG.md, Data/Techion.rte/Devices/Weapons/Nucleo/NucleoShot.lua
Give them a few defaults to some variables that disappear when save/loading
It's not really worth it bringing in SaveLoadHandler and saving all this stuff properly, because something in the middle of an explosion sequence is... about to explode anyway
=> Fix nucleo shots breaking if loading mid-explosion-sequence

CHANGELOG.md, Data/Base.rte/Activities/BrainVsBrain.lua, Data/Base.rte/Activities/Harvester.lua, Data/Base.rte/Activities/KeepieUppie.lua, Data/Base.rte/Activities/Massacre.lua, Data/Base.rte/Activities/MetaFight.lua, Data/Base.rte/Activities/OneManArmy.lua, Data/Base.rte/Activities/OneManArmyDiggers.lua, Data/Base.rte/Activities/OneManArmyZeroG.lua, Data/Base.rte/Activities/Siege.lua, Data/Base.rte/Activities/SkirmishDefense.lua, Data/Base.rte/Activities/Survival.lua, Data/Base.rte/Activities/Test.lua, Data/Base.rte/Activities/WaveDefense.lua, Data/Missions.rte/Activities/DecisionDay.lua, Data/Missions.rte/Activities/Doainar.lua, Data/Missions.rte/Activities/DummyAssault.lua, Data/Missions.rte/Activities/Maginot.lua, Data/Missions.rte/Activities/SignalHunt.lua
`FrameMan.ClearScreenText()` and `FrameMan.SetScreenText()` take a screen index, but are regularly passed a player index instead. If the players aren't all sequential (e.g. player 2 and player 4 are playing), then some or all of these functions may operate on the wrong screen, or no screen at all. Fortunately, some activities correctly call `Activity.ScreenOfPlayer()`, so they didn't *all* need fixing.
Additionally, some activities iterated over players incorrectly, going from `0` to `PlayerCount - 1` instead of iterating from `PLAYER_1` to `MAXPLAYERCOUNT - 1` and filtering for active human players. This made Exploration (Doainar) impossible to progress if you decided to use a different player than player 1.
Lastly, some activities intentionally displayed a message only for `PLAYER_1`. …
=> Activities: Be more consistent about passing screens, some fixes.

CHANGELOG.md, Data/Browncoats.rte/Devices.ini, Data/Imperatus.rte/Actors/Shared.ini
Disable item that was showing up in random scripts that merely scanned for Buyable
Nerf imperatus jetpack to make it not the strongest in the game
=> Minor fix and balance

CHANGELOG.md, Data/Base.rte/Activities/BunkerBreach.lua, Data/Base.rte/Activities/Survival.lua
Fixes doors being owned by the wrong team because they'd just follow whatever the Scene had them set as
=> Survival and BunkerBreach explicitly set door ownership

CHANGELOG.md, Source/System/Atom.cpp
Previously, `IgnoreTerrain` on `MovableObjects` would have little to no effect on terrain collisions; now it correctly toggles all terrain collisions.
=> Fixed IgnoreTerrain not having any effect

CHANGELOG.md, Data/Base.rte/Activities/Harvester.lua, Data/Base.rte/Activities/KeepieUppie.lua, Data/Base.rte/Activities/Massacre.lua, Data/Base.rte/Activities/OneManArmy.lua, Data/Base.rte/Activities/OneManArmyDiggers.lua, Data/Base.rte/Activities/Survival.lua, Data/Missions.rte/Activities/DecisionDay.lua, Data/Missions.rte/Activities/SignalHunt.lua, Resources/Credits.h
Signal Hunt was only checking to see if speedrun mode should be disabled if Player 1 had a brainbot, so if you used a different player, you could activate speedrun mode after deploying and spending all your gold, somewhat undercutting the point of speedrun mode. The check now scans over every player to look for brainbots, and additionally, `DoSpeedrunMode()` also iterates over all players looking for the rocket instead of assuming Player 1 (actually a hardcoded index 0) is active.
On an unrelated note, `DoSecret()` now calls `SwitchToActor()` on the brainbot after changing its team so that it's not left under AI control until you swap back to it. It also skips setting the AI mode and target for player-controlled actors, so your brainbot won't get an automatic goto order. However, if using …
=> Activities: Fix more player 1 assumptions, make broken code to avoid deploying on a player work.

CHANGELOG.md, Source/Menus/MetagameGUI.cpp, Source/Menus/MetagameGUI.h, Source/Menus/ScenarioActivityConfigGUI.cpp
Every time `MetagameGUI::SetEnabled()` was called, each player's tech selection dropdown would get all its entries added to it again. Since the selection code relied on "-Random-" being the first element of the dropdown, if any other "-Random-" entry were selected (even by the random selecvtion code itself!), the player's `m_NativeTechModule` would get set to `-1`. The same commit that moved the code to `MetagameGUI::SetEnabled()` also did something similar to `ScenarioActivityConfigGUI`, but with one key difference: a boolean flag to determine whether or not that loading had occurred. By adding the same to `MetagameUI`, it can be ensured that the tech list only gets populated once.
Additionally, the code was calling `m_apPlayerTechSelect[player]->GetListPanel()->ScrollToTop()` after …
=> Gate populating metagame tech dropdown and team icons behind flag.

CHANGELOG.md, Source/Entities/HDFirearm.cpp, Source/Entities/HDFirearm.h, Source/Lua/LuaBindingsEntities.cpp
does what it says on the tin
NOTE: the equivalent Muzzle variants of these bindings are defined blankly in HeldDevice and then overriden in HDFirearm. this felt completely vestigial and pointless, so i made THESE bindings just directly in HDFirearm.
=> Add missing HDFirearm EjectionOffset and EjectionPos bindings

CHANGELOG.md, Data/Base.rte/Devices/Tools/Constructor/Constructor.lua
If "Order Construction" was actively selected instead of letting it be selected by releasing the pie menu button, the script would detect the `PIE_MENU_ACTIVE` control and immediately cancel the controller. I added a variable to track whether or not `PIE_MENU_ACTIVE` is still held from the option being selected, and to ignore it if so.
=> Fix Constructor instantly cancelling the build cursor sometimes.

CHANGELOG.md, Data/Base.rte/Activities/Massacre.lua, Data/Base.rte/Activities/OneManArmy.lua, Data/Base.rte/Activities/OneManArmyDiggers.lua, Data/Base.rte/Activities/Survival.lua
Apparently I got distracted partway through and forgot what I was doing, because I only got rid of the last reference to the now-removed loop variable `i` in Harvester and KeepieUppie, leaving Massacre, OneManArmy, OneManArmyDiggers, and Survival broken. Whoops!
=> Fix regression added in #99 that prevented enemies from spawning.

CHANGELOG.md, Source/Entities/AHuman.cpp, Source/Entities/Arm.cpp
If a gun had SupportOffsetWhileReloading == true and you modified it's Supportable value to be only true while reloading (and false when not), the hand wouldn't support the gun on the reload. 
The one handed penalty is still applied to the reload, since the gun reloads quicker than the hand reaches the gun. 
Nothing a few lines of code in lua to restrict the reload can't fix for modders that care about it
=> Fixed issue regarding Supportable and SupportOffsetWhileReloading

CHANGELOG.md, Source/Entities/MovableObject.h, Source/Lua/LuaBindingsEntities.cpp
`EffectAlwaysShows` is necessary for most MOSR's to show their glows at all, and this would permit adding visible glows to MOSR's that otherwise lack this property.
=> Exposed EffectAlwaysShows to Lua
